global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR

api:
  dashboard: true
  # insecure: false  # Keep false and use authentication if exposing dashboard

entryPoints:
  web:
    address: ":80"

providers:
  swarm:
    network: backend
    exposedByDefault: false
    watch: true